// lib/sample-data.ts
import { CompletedSale, Product, Coupon, SavedOrder, StoreSettings, RegisterLease, AuditEvent } from './types';

export const sampleProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'Espresso Americano (Hot)',
    pricePaise: 18000,
    barcode: '8901234567890',
    category: 'Beverages',
    stock: 45,
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    _rev: 1,
    _lastModifiedBy: 'ADMIN_WEB',
  },
  {
    id: 'prod_2',
    name: 'Butter Croissant',
    pricePaise: 15000,
    barcode: '8901234567891',
    category: 'Bakery',
    stock: 18,
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    _rev: 1,
    _lastModifiedBy: 'POS_DEVICE',
  },
  {
    id: 'prod_3',
    name: 'Iced Caramel Macchiato',
    pricePaise: 24000,
    barcode: '8901234567892',
    category: 'Beverages',
    stock: 8,
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    _rev: 2,
    _lastModifiedBy: 'ADMIN_WEB',
  },
  {
    id: 'prod_4',
    name: 'Smoked Paneer Panini',
    pricePaise: 22000,
    barcode: '8901234567893',
    category: 'Food',
    stock: 0,
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 10 * 60 * 1000,
    _rev: 3,
    _lastModifiedBy: 'POS_DEVICE',
  },
  {
    id: 'prod_5',
    name: 'Belgian Chocolate Muffin',
    pricePaise: 12000,
    barcode: '8901234567894',
    category: 'Bakery',
    stock: 24,
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    _rev: 1,
    _lastModifiedBy: 'ADMIN_WEB',
  },
  {
    id: 'prod_6',
    name: 'Masala Chai Latte',
    pricePaise: 11000,
    barcode: '8901234567895',
    category: 'Beverages',
    stock: 60,
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    _rev: 1,
    _lastModifiedBy: 'ADMIN_WEB',
  },
  {
    id: 'prod_7',
    name: 'Crispy Veggie Wrap',
    pricePaise: 19500,
    barcode: '8901234567896',
    category: 'Food',
    stock: 12,
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    _rev: 1,
    _lastModifiedBy: 'ADMIN_WEB',
  }
];

const now = Date.now();
const hour = 60 * 60 * 1000;

export const sampleSales: CompletedSale[] = [
  {
    id: 'sale_101',
    invoiceNumber: 'INV-2026-0042',
    orderNumber: 'ORD-101',
    createdAt: now - 35 * 60 * 1000,
    updatedAt: now - 35 * 60 * 1000,
    completedAt: now - 35 * 60 * 1000,
    customer: { name: 'Aarav Sharma', phone: '+91 98765 43210', email: 'aarav@example.com' },
    items: [
      { id: 'prod_1', name: 'Espresso Americano (Hot)', unitPricePaise: 18000, quantity: 2 },
      { id: 'prod_2', name: 'Butter Croissant', unitPricePaise: 15000, quantity: 1 },
    ],
    subtotalPaise: 51000,
    taxPaise: 2550,
    discountPaise: 5000,
    grandTotalPaise: 48550,
    paymentMethod: 'upi',
    amountPaidPaise: 48550,
    changePaise: 0,
    status: 'completed',
    appliedCouponCode: 'WELCOME50',
    appliedCouponId: 'coup_1',
    registerCode: 'REG-A',
    registrationEpoch: 1,
    _rev: 1,
    _lastModifiedBy: 'POS_DEVICE',
  },
  {
    id: 'sale_102',
    invoiceNumber: 'INV-2026-0043',
    orderNumber: 'ORD-102',
    createdAt: now - 2 * hour,
    updatedAt: now - 2 * hour,
    completedAt: now - 2 * hour,
    customer: { name: 'Pooja Verma', phone: '+91 98111 22233' },
    items: [
      { id: 'prod_3', name: 'Iced Caramel Macchiato', unitPricePaise: 24000, quantity: 1 },
      { id: 'prod_5', name: 'Belgian Chocolate Muffin', unitPricePaise: 12000, quantity: 2 },
    ],
    subtotalPaise: 48000,
    taxPaise: 2400,
    discountPaise: 0,
    grandTotalPaise: 50400,
    paymentMethod: 'cash',
    amountPaidPaise: 60000,
    changePaise: 9600,
    status: 'completed',
    registerCode: 'REG-A',
    registrationEpoch: 1,
    _rev: 1,
    _lastModifiedBy: 'POS_DEVICE',
  },
  {
    id: 'sale_103',
    invoiceNumber: 'INV-2026-0044',
    orderNumber: 'ORD-103',
    createdAt: now - 4 * hour,
    updatedAt: now - 3 * hour,
    completedAt: now - 4 * hour,
    customer: { name: 'Vikram Mehta', phone: '+91 97234 56789' },
    items: [
      { id: 'prod_4', name: 'Smoked Paneer Panini', unitPricePaise: 22000, quantity: 2 },
      { id: 'prod_6', name: 'Masala Chai Latte', unitPricePaise: 11000, quantity: 2 },
    ],
    subtotalPaise: 66000,
    taxPaise: 3300,
    discountPaise: 0,
    grandTotalPaise: 69300,
    paymentMethod: 'card',
    amountPaidPaise: 69300,
    changePaise: 0,
    status: 'cancelled',
    cancelledAt: now - 3 * hour,
    registerCode: 'REG-B',
    registrationEpoch: 2,
    _rev: 2,
    _lastModifiedBy: 'ADMIN_WEB',
  },
  {
    id: 'sale_104',
    invoiceNumber: 'INV-2026-0045',
    orderNumber: 'ORD-104',
    createdAt: now - 6 * hour,
    updatedAt: now - 6 * hour,
    completedAt: now - 6 * hour,
    items: [
      { id: 'prod_7', name: 'Crispy Veggie Wrap', unitPricePaise: 19500, quantity: 1 },
      { id: 'prod_1', name: 'Espresso Americano (Hot)', unitPricePaise: 18000, quantity: 1 },
    ],
    subtotalPaise: 37500,
    taxPaise: 1875,
    discountPaise: 0,
    grandTotalPaise: 39375,
    paymentMethod: 'split',
    amountPaidPaise: 39375,
    changePaise: 0,
    status: 'completed',
    registerCode: 'REG-A',
    registrationEpoch: 1,
    _rev: 1,
    _lastModifiedBy: 'POS_DEVICE',
  },
  {
    id: 'sale_105',
    invoiceNumber: 'INV-2026-0039',
    orderNumber: 'ORD-099',
    createdAt: now - 26 * hour,
    updatedAt: now - 26 * hour,
    completedAt: now - 26 * hour,
    customer: { name: 'Rohit Gupta', phone: '+91 99887 76655' },
    items: [
      { id: 'prod_1', name: 'Espresso Americano (Hot)', unitPricePaise: 18000, quantity: 3 },
      { id: 'prod_5', name: 'Belgian Chocolate Muffin', unitPricePaise: 12000, quantity: 3 },
    ],
    subtotalPaise: 90000,
    taxPaise: 4500,
    discountPaise: 9000,
    grandTotalPaise: 85500,
    paymentMethod: 'upi',
    amountPaidPaise: 85500,
    changePaise: 0,
    status: 'completed',
    appliedCouponCode: 'FLAT10',
    appliedCouponId: 'coup_2',
    registerCode: 'REG-B',
    registrationEpoch: 2,
    _rev: 1,
    _lastModifiedBy: 'POS_DEVICE',
  },
  {
    id: 'sale_106',
    invoiceNumber: 'INV-2026-0035',
    orderNumber: 'ORD-095',
    createdAt: now - 48 * hour,
    updatedAt: now - 48 * hour,
    completedAt: now - 48 * hour,
    customer: { name: 'Sneha Patel', phone: '+91 98450 12345' },
    items: [
      { id: 'prod_2', name: 'Butter Croissant', unitPricePaise: 15000, quantity: 2 },
      { id: 'prod_6', name: 'Masala Chai Latte', unitPricePaise: 11000, quantity: 2 },
    ],
    subtotalPaise: 52000,
    taxPaise: 2600,
    discountPaise: 0,
    grandTotalPaise: 54600,
    paymentMethod: 'card',
    amountPaidPaise: 54600,
    changePaise: 0,
    status: 'completed',
    registerCode: 'REG-A',
    registrationEpoch: 1,
    _rev: 1,
    _lastModifiedBy: 'POS_DEVICE',
  }
];

export const sampleAuditEvents: Record<string, AuditEvent[]> = {
  sale_101: [
    {
      id: 'aud_1',
      saleId: 'sale_101',
      actorUid: 'usr_owner_123',
      operationId: 'op_init_1',
      rev: 1,
      operationType: 'CREATE',
      source: 'POS_DEVICE',
      timestamp: now - 35 * 60 * 1000,
      details: { invoiceNumber: 'INV-2026-0042', grandTotalPaise: 48550 }
    }
  ],
  sale_103: [
    {
      id: 'aud_2',
      saleId: 'sale_103',
      actorUid: 'usr_owner_123',
      operationId: 'op_init_2',
      rev: 1,
      operationType: 'CREATE',
      source: 'POS_DEVICE',
      timestamp: now - 4 * hour,
      details: { invoiceNumber: 'INV-2026-0044', grandTotalPaise: 69300 }
    },
    {
      id: 'aud_3',
      saleId: 'sale_103',
      actorUid: 'usr_owner_123',
      operationId: 'op_cancel_1',
      rev: 2,
      operationType: 'CANCEL',
      source: 'ADMIN_WEB',
      timestamp: now - 3 * hour,
      details: { reason: 'Customer requested cancellation prior to prep', reversedCoupon: false }
    }
  ]
};

export const sampleCoupons: Coupon[] = [
  {
    id: 'coup_1',
    code: 'WELCOME50',
    amountPaise: 5000,
    type: 'fixed',
    status: 'active',
    createdAt: now - 15 * 24 * hour,
    usageLimit: 50,
    usageCount: 14,
    _rev: 1,
  },
  {
    id: 'coup_2',
    code: 'FLAT10',
    amountPaise: 0,
    discountPercent: 10,
    type: 'percent',
    status: 'active',
    createdAt: now - 10 * 24 * hour,
    usageLimit: null,
    usageCount: 38,
    _rev: 1,
  },
  {
    id: 'coup_3',
    code: 'VIPGUEST',
    amountPaise: 10000,
    type: 'fixed',
    status: 'active',
    createdAt: now - 5 * 24 * hour,
    expiresAt: now + 15 * 24 * hour,
    customerName: 'Aarav Sharma',
    usageLimit: 1,
    usageCount: 0,
    _rev: 1,
  },
  {
    id: 'coup_4',
    code: 'EXPIRED100',
    amountPaise: 10000,
    type: 'fixed',
    status: 'expired',
    createdAt: now - 60 * 24 * hour,
    expiresAt: now - 10 * 24 * hour,
    usageLimit: 10,
    usageCount: 10,
    _rev: 1,
  }
];

export const sampleSavedOrders: SavedOrder[] = [
  {
    id: 'order_park_1',
    orderNumber: 'HOLD-001',
    createdAt: now - 18 * 60 * 1000,
    updatedAt: now - 18 * 60 * 1000,
    customer: { name: 'Kavita Singh', phone: '+91 98711 00223' },
    items: [
      { id: 'prod_1', name: 'Espresso Americano (Hot)', unitPricePaise: 18000, quantity: 2 },
      { id: 'prod_3', name: 'Iced Caramel Macchiato', unitPricePaise: 24000, quantity: 1 }
    ],
    subtotalPaise: 60000,
    taxPaise: 3000,
    discountPaise: 0,
    grandTotalPaise: 63000,
    status: 'draft',
    _rev: 1,
  },
  {
    id: 'order_park_2',
    orderNumber: 'HOLD-002',
    createdAt: now - 45 * 60 * 1000,
    updatedAt: now - 45 * 60 * 1000,
    items: [
      { id: 'prod_4', name: 'Smoked Paneer Panini', unitPricePaise: 22000, quantity: 1 },
      { id: 'prod_2', name: 'Butter Croissant', unitPricePaise: 15000, quantity: 2 }
    ],
    subtotalPaise: 52000,
    taxPaise: 2600,
    discountPaise: 0,
    grandTotalPaise: 54600,
    status: 'draft',
    _rev: 1,
  }
];

export const sampleRegisters: RegisterLease[] = [
  {
    id: 'reg_a',
    registerCode: 'REG-A',
    ownerDeviceId: 'dev_pixel7a_counter1',
    deviceName: 'Pixel 7a (Main Counter)',
    leaseStatus: 'ACTIVE',
    registrationEpoch: 1,
    leaseExpiresAt: now + 7 * 24 * hour,
    lastSyncAt: now - 2 * 60 * 1000,
    createdAt: now - 60 * 24 * hour,
  },
  {
    id: 'reg_b',
    registerCode: 'REG-B',
    ownerDeviceId: 'dev_samsung_counter2',
    deviceName: 'Galaxy Tab S8 (Drive-Thru / Patio)',
    leaseStatus: 'ACTIVE',
    registrationEpoch: 2,
    leaseExpiresAt: now + 5 * 24 * hour,
    lastSyncAt: now - 12 * 60 * 1000,
    createdAt: now - 45 * 24 * hour,
  }
];

export const sampleSettings: StoreSettings = {
  businessName: 'Quick Bill Café & Artisan Bakery',
  businessAddress: 'Plot 42, Cyber Hub, Phase 2, Gurugram, Haryana 122002',
  businessPhone: '+91 124 456 7890',
  gstin: '06AAAAA0000A1Z5',
  taxRatePercent: 5,
  taxEnabled: true,
  receiptHeader: 'Welcome to Quick Bill Café\nFresh Brews & Oven Treats',
  receiptFooter: 'Thank you for dining with us!\nPlease visit again.',
  showShopName: true,
  showShopAddress: true,
  showShopPhone: true,
  showShopGstin: true,
  showThankYouMessage: true,
  _rev: 1,
};
